version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-net
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASS:-adminpass}
      POSTGRES_DB: ${DB_NAME:-mydb}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net: